Algoritmo "Exibir Mensagem"
// Disciplina  : [Lógica de Proramação e Javascript]
// Jailson     : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Francisco Pinheiro Guedes
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Francisco - Ferraz")
Escreval ("Equipe 04")
Escreva ("Chico")
Fimalgoritmo